# Generated by Django 4.0.3 on 2022-03-17 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_alter_comment_dislikes_alter_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube.comment'),
        ),
    ]
