# Generated by Django 4.0.3 on 2022-03-17 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_alter_reply_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='youtube.comment'),
            preserve_default=False,
        ),
    ]
